version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
      - nvm install 8
      - nvm use 8
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`